#MODE CONSTANTS
PRE = "pre"
AP = "ap"
#SERVER RETURN MESSAGES CONSTANTS
STORED = "STORED\0"
EXISTS = "EXISTS\0"
NOT_STORED = "NOT_STORED\0"
NOT_FOUND = "NOT_FOUND\0"
END_STRING = "END\0"
ERROR = "ERROR\0"
CLIENT_ERROR_BAD_CHUNK = "CLIENT_ERROR bad data chunk\0"
INSERT_VALUE = "insertvalue\0" #string returned by server when expecting data from user
END_TRANSMISION = "\0"

#AMOUNT OF SECONDS IN 30 DAYS
DAYS_30 = 2592000
